services:
  - type: web
    name: interviewai-backend
    runtime: docker
    repo: https://github.com/maneeth17/ai_interview
    region: oregon
    plan: free
    branch: main
    dockerfilePath: ./backend/Dockerfile
    healthCheckPath: /api/health
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: BACKEND_URL
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: USE_REMOTE_DATABASE
        value: "true"
      - key: DATABASE_URL
        sync: false
